// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="image_processing_image_processing,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.869829,HLS_SYN_LAT=25956,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=11075,HLS_SYN_LUT=18379,HLS_VERSION=2022_2}" *)

module image_processing (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        frame_in_pixel_address0,
        frame_in_pixel_ce0,
        frame_in_pixel_q0,
        frame_in_pixel_address1,
        frame_in_pixel_ce1,
        frame_in_pixel_q1,
        frame_in_width,
        frame_in_height,
        frame_out1_pixel_address0,
        frame_out1_pixel_ce0,
        frame_out1_pixel_we0,
        frame_out1_pixel_d0,
        frame_out1_width,
        frame_out1_height,
        frame_out2_pixel_address0,
        frame_out2_pixel_ce0,
        frame_out2_pixel_we0,
        frame_out2_pixel_d0,
        frame_out2_width,
        frame_out2_height,
        frame_out3_pixel_address0,
        frame_out3_pixel_ce0,
        frame_out3_pixel_we0,
        frame_out3_pixel_d0,
        frame_out3_width,
        frame_out3_height,
        frame_out5_pixel_address0,
        frame_out5_pixel_ce0,
        frame_out5_pixel_we0,
        frame_out5_pixel_d0,
        frame_out5_width,
        frame_out5_height,
        frame_out6_pixel_address0,
        frame_out6_pixel_ce0,
        frame_out6_pixel_we0,
        frame_out6_pixel_d0,
        frame_out6_width,
        frame_out6_height,
        frame_out8_pixel_address0,
        frame_out8_pixel_ce0,
        frame_out8_pixel_we0,
        frame_out8_pixel_d0,
        frame_out8_width,
        frame_out8_height,
        frame_out9_pixel_address0,
        frame_out9_pixel_ce0,
        frame_out9_pixel_we0,
        frame_out9_pixel_d0,
        frame_out9_width,
        frame_out9_height
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [12:0] frame_in_pixel_address0;
output   frame_in_pixel_ce0;
input  [95:0] frame_in_pixel_q0;
output  [12:0] frame_in_pixel_address1;
output   frame_in_pixel_ce1;
input  [95:0] frame_in_pixel_q1;
input  [31:0] frame_in_width;
input  [31:0] frame_in_height;
output  [12:0] frame_out1_pixel_address0;
output   frame_out1_pixel_ce0;
output   frame_out1_pixel_we0;
output  [95:0] frame_out1_pixel_d0;
input  [31:0] frame_out1_width;
input  [31:0] frame_out1_height;
output  [12:0] frame_out2_pixel_address0;
output   frame_out2_pixel_ce0;
output   frame_out2_pixel_we0;
output  [95:0] frame_out2_pixel_d0;
input  [31:0] frame_out2_width;
input  [31:0] frame_out2_height;
output  [12:0] frame_out3_pixel_address0;
output   frame_out3_pixel_ce0;
output   frame_out3_pixel_we0;
output  [95:0] frame_out3_pixel_d0;
input  [31:0] frame_out3_width;
input  [31:0] frame_out3_height;
output  [12:0] frame_out5_pixel_address0;
output   frame_out5_pixel_ce0;
output   frame_out5_pixel_we0;
output  [95:0] frame_out5_pixel_d0;
input  [31:0] frame_out5_width;
input  [31:0] frame_out5_height;
output  [12:0] frame_out6_pixel_address0;
output   frame_out6_pixel_ce0;
output   frame_out6_pixel_we0;
output  [95:0] frame_out6_pixel_d0;
input  [31:0] frame_out6_width;
input  [31:0] frame_out6_height;
output  [12:0] frame_out8_pixel_address0;
output   frame_out8_pixel_ce0;
output   frame_out8_pixel_we0;
output  [95:0] frame_out8_pixel_d0;
input  [31:0] frame_out8_width;
input  [31:0] frame_out8_height;
output  [12:0] frame_out9_pixel_address0;
output   frame_out9_pixel_ce0;
output   frame_out9_pixel_we0;
output  [95:0] frame_out9_pixel_d0;
input  [31:0] frame_out9_width;
input  [31:0] frame_out9_height;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] empty_23_fu_116_p2;
reg   [6:0] empty_23_reg_130;
wire   [12:0] add_ln204_fu_123_p2;
reg   [12:0] add_ln204_reg_135;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_idle;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_ready;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address1;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce1;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_d0;
wire   [12:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_address0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_ce0;
wire    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_we0;
wire   [95:0] grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_d0;
reg    grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [6:0] empty_fu_112_p1;
wire   [12:0] trunc_ln165_fu_108_p1;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg = 1'b0;
end

image_processing_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2 grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start),
    .ap_done(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done),
    .ap_idle(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_idle),
    .ap_ready(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_ready),
    .empty(empty_23_reg_130),
    .frame_in_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address0),
    .frame_in_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce0),
    .frame_in_pixel_q0(frame_in_pixel_q0),
    .frame_in_pixel_address1(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address1),
    .frame_in_pixel_ce1(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce1),
    .frame_in_pixel_q1(frame_in_pixel_q1),
    .frame_out1_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_address0),
    .frame_out1_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_ce0),
    .frame_out1_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_we0),
    .frame_out1_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_d0),
    .frame_out2_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_address0),
    .frame_out2_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_ce0),
    .frame_out2_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_we0),
    .frame_out2_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_d0),
    .frame_out3_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_address0),
    .frame_out3_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_ce0),
    .frame_out3_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_we0),
    .frame_out3_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_d0),
    .frame_out5_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_address0),
    .frame_out5_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_ce0),
    .frame_out5_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_we0),
    .frame_out5_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_d0),
    .frame_out6_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_address0),
    .frame_out6_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_ce0),
    .frame_out6_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_we0),
    .frame_out6_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_d0),
    .frame_out8_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_address0),
    .frame_out8_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_ce0),
    .frame_out8_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_we0),
    .frame_out8_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_d0),
    .frame_out9_pixel_address0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_address0),
    .frame_out9_pixel_ce0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_ce0),
    .frame_out9_pixel_we0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_we0),
    .frame_out9_pixel_d0(grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_d0),
    .add_ln204(add_ln204_reg_135)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_ready == 1'b1)) begin
            grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        add_ln204_reg_135 <= add_ln204_fu_123_p2;
        empty_23_reg_130 <= empty_23_fu_116_p2;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln204_fu_123_p2 = ($signed(trunc_ln165_fu_108_p1) + $signed(13'd8191));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign empty_23_fu_116_p2 = ($signed(empty_fu_112_p1) + $signed(7'd127));

assign empty_fu_112_p1 = frame_in_height[6:0];

assign frame_in_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address0;

assign frame_in_pixel_address1 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_address1;

assign frame_in_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce0;

assign frame_in_pixel_ce1 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_in_pixel_ce1;

assign frame_out1_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_address0;

assign frame_out1_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_ce0;

assign frame_out1_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_d0;

assign frame_out1_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out1_pixel_we0;

assign frame_out2_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_address0;

assign frame_out2_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_ce0;

assign frame_out2_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_d0;

assign frame_out2_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out2_pixel_we0;

assign frame_out3_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_address0;

assign frame_out3_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_ce0;

assign frame_out3_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_d0;

assign frame_out3_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out3_pixel_we0;

assign frame_out5_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_address0;

assign frame_out5_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_ce0;

assign frame_out5_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_d0;

assign frame_out5_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out5_pixel_we0;

assign frame_out6_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_address0;

assign frame_out6_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_ce0;

assign frame_out6_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_d0;

assign frame_out6_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out6_pixel_we0;

assign frame_out8_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_address0;

assign frame_out8_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_ce0;

assign frame_out8_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_d0;

assign frame_out8_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out8_pixel_we0;

assign frame_out9_pixel_address0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_address0;

assign frame_out9_pixel_ce0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_ce0;

assign frame_out9_pixel_d0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_d0;

assign frame_out9_pixel_we0 = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_frame_out9_pixel_we0;

assign grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start = grp_image_processing_Pipeline_VITIS_LOOP_165_1_VITIS_LOOP_166_2_fu_86_ap_start_reg;

assign trunc_ln165_fu_108_p1 = frame_in_width[12:0];

endmodule //image_processing
