# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/P V S Sukeerthi/Desktop/project_set2/project_set2.srcs/sources_1/ip/image_processing_0/image_processing_0.xci
# IP: The module: 'image_processing_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/P V S Sukeerthi/Desktop/project_set2/project_set2.gen/sources_1/ip/image_processing_0/constraints/image_processing_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_processing_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/P V S Sukeerthi/Desktop/project_set2/project_set2.srcs/sources_1/ip/image_processing_0/image_processing_0.xci
# IP: The module: 'image_processing_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/P V S Sukeerthi/Desktop/project_set2/project_set2.gen/sources_1/ip/image_processing_0/constraints/image_processing_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'image_processing_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
